db:
  url: "postgres://postgres:postgres@localhost:5432/brahmafi?sslmode=disable"
  migrations:
    dir: "file://migrations"

logger:
  name: brahmafi
  level: DEBUG

chain:
  rpc-url: "wss://mainnet.infura.io/ws/v3/d55be5e641974915a3d3fadc53bd3e88"
  block-rate: 12
  pools:
    - "0xCBCdF9626bC03E24f779434178A73a0B4bad62eD"
